### ISSUE TITLE
No virtual method getColor(I)I 红米note2，安卓 5.02，MIUI8.1

### ISSUE THREAD

**Issue by FanYimin** [martin90s/ImagePicker#1]
01-22 11:48:41.244 17987-17987/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.imnjh.imagepickersample, PID: 17987
                                                   java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Lcom/imnjh/imagepickersample/app/PickerApplication; or its super classes (declaration of 'com.imnjh.imagepickersample.app.PickerApplication' appears in /data/data/com.imnjh.imagepickersample/files/instant-run/dex/slice-slice_3-classes.dex)
                                                       at com.imnjh.imagepickersample.app.PickerApplication.onCreate(PickerApplication.java:25)
                                                       at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4762)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by martin90s** [comment]
@FanYimin 已修复，拉下代码，暂时不发新版
