### ISSUE TITLE
预览卡顿的问题

### ISSUE THREAD

**Issue by hike2008** [martin90s/ImagePicker#14]
小米note3， 预览图片， 滑动到系统相机拍的照片切换时， 有明显的卡顿；

W/ExifInterface: Invalid image.
                                                                 java.io.IOException: Invalid marker: 89
                                                                     at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1616)
                                                                     at android.media.ExifInterface.loadAttributes(ExifInterface.java:1341)
                                                                     at android.media.ExifInterface.<init>(ExifInterface.java:1058)
                                                                     at com.imnjh.imagepicker.widget.subsamplingview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1861)
                                                                     at com.imnjh.imagepicker.widget.subsamplingview.SubsamplingScaleImageView.access$4900(SubsamplingScaleImageView.java:81)
                                                                     at com.imnjh.imagepicker.widget.subsamplingview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1749)
                                                                     at com.imnjh.imagepicker.widget.subsamplingview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1717)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
06-09 15:00:00.886 22853-22853 I/Foreground: went background
06-09 15:14:48.411 22853-22863 I/art: Background sticky concurrent mark sweep GC freed 127860(13MB) AllocSpace objects, 9(236KB) LOS objects, 6% free, 164MB/175MB, paused 2.219ms total 101.235ms

**Comment by hike2008** [comment]
将 PicturePreviewPageView 换成使用PhotoView则不卡顿
