### ISSUE TITLE
相册列表点击查看图片时候崩溃 已经注册清单文件了还是不行

### ISSUE THREAD

**Issue by liangweihao** [martin90s/ImagePicker#22]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.imnjh.imagepicker.activity.PickerPreviewActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                      at android.os.Looper.loop(Looper.java:207)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5939)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
                                                                   Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                      at android.view.ViewGroup.addView(ViewGroup.java:4206)
                                                                      at android.view.ViewGroup.addView(ViewGroup.java:4188)
                                                                      at com.imnjh.imagepicker.activity.PickerPreviewActivity.initUI(PickerPreviewActivity.java:222)
                                                                      at com.imnjh.imagepicker.activity.PickerPreviewActivity.onCreate(PickerPreviewActivity.java:122)

**Comment by liangweihao** [comment]
好了  找到问题了  createImageView 没有配置
