### ISSUE TITLE
Could not find method android.widget.Spinner.getPopupContext,

### ISSUE THREAD

**Issue by gyb3320** [martin90s/ImagePicker#3]
I/dalvikvm: Could not find method android.widget.Spinner.getPopupContext, referenced from method android.support.v7.widget.AppCompatSpinner.getPopupContext

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.yobn.yobnsample, PID: 20587
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yobn.yobnsample/com.imnjh.imagepicker.activity.PhotoPickerActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.AppCompatSpinner
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2263)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                      at android.app.ActivityThread.access$800(ActivityThread.java:147)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5137)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.AppCompatSpinner
                      at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.initUI(PhotoPickerActivity.java:177)
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:137)
                      at android.app.Activity.performCreate(Activity.java:5231)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2227)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1226) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5137) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by martin90s** [comment]
@gyb3320 new version has fix this error
