### ISSUE TITLE
example app crash on android 4.4 and below

### ISSUE THREAD

**Issue by stepsame** [martin90s/ImagePicker#6]
test phones: Meizu MX3(4.4.4), MI NOTE LTE(4.4.4), Galaxy S4(4.3)

error log:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.imnjh.imagepickersample, PID: 8101
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.imnjh.imagepickersample/com.imnjh.imagepicker.activity.PhotoPickerActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.AppCompatSpinner
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
                      at android.app.ActivityThread.access$800(ActivityThread.java:136)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5032)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.AppCompatSpinner
                      at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.initUI(PhotoPickerActivity.java:177)
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:137)
                      at android.app.Activity.performCreate(Activity.java:5310)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:136) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5032) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.initUI(PhotoPickerActivity.java:177) 
                      at com.imnjh.imagepicker.activity.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:137) 
                      at android.app.Activity.performCreate(Activity.java:5310) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2179) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:136) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1219) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5032) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by martin90s** [comment]
@stepsame have u try the new version? i fixed this error in new version

**Comment by stepsame** [comment]
@martin90s 今天 git clone 下来的，应该是最新的吧，还需要提供一些什么信息吗？主要想调用该库作为一个cordova插件，现在5.0系统以上都没有问题

**Comment by bigtotorouk** [comment]
这个问题还没有解决 。哎。

**Comment by martin90s** [comment]
@bigtotorouk fixed. please try the latest version

**Comment by sxying** [comment]
为什么我用了新版本还是会出现上面的错误....
